{{- if and (.Values.service) (.Values.service.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  {{- if .Values.service.extraPorts }}
    {{- toYaml .Values.service.extraPorts | nindent 4 }}
  {{- end }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
